services:
  api_gateway:
    platform: linux/amd64
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: netskyplot-api-gateway
    ports:
      - "8760:5000"
    networks:
      - net-skyplot

  data_integrator:
    platform: linux/amd64
    build:
      context: ./data_integrator
      dockerfile: Dockerfile
    container_name: netskyplot-data-integrator
    ports:
      - "8761:5001"
    networks:
      - net-skyplot

  computations:
    platform: linux/amd64
    build:
      context: ./computations
      dockerfile: Dockerfile
    container_name: netskyplot-computations
    ports:
      - "8762:5002"
    depends_on:
      - data_integrator
    networks:
      - net-skyplot

networks:
  net-skyplot:
    driver: bridge
